"""Introduce game comments.

Revision ID: 1e63b784275
Revises: 5a5c741ba561
Create Date: 2015-06-23 12:07:26.990224

"""

# revision identifiers, used by Alembic.
revision = '1e63b784275'
down_revision = '5a5c741ba561'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('game_comment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pub_date', sa.DateTime(), nullable=True),
    sa.Column('game_id', sa.Integer(), nullable=True),
    sa.Column('content', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['game_id'], ['games.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('game_comment')
    ### end Alembic commands ###
