"""basic User table

Revision ID: 43e4e3402b9
Revises: 2dfb5e99f2c
Create Date: 2015-06-29 17:20:58.330935

"""

# revision identifiers, used by Alembic.
revision = '43e4e3402b9'
down_revision = '2dfb5e99f2c'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('username', sa.String(length=254), nullable=True),
        sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    ### end Alembic commands ###
